Use correct socket path for linux
davidalger/warden pull request #334
Opened 2021-03-25 19:46 UTC by alinalexandru

Fixes #331

I explained in ticket the reason to set the `SSH_AUTH_SOCK` environment variable

2021-03-26 07:46 UTC, ihor-sviziev commented
Hi @alinalexandru,
I believe it won't work correctly in case if your user id on the host machine not equal to 1000. 
Here are more details about that: https://github.com/davidalger/warden/pull/307#issuecomment-781921198 https://github.com/davidalger/warden/pull/307#issuecomment-783863500

2021-03-26 13:23 UTC, alinalexandru commented
You are right with the user id.
The issue with user with ID 1000 still exists. This week I had to change the user ID to 1000 so that I could fix the `composer/cache` permissions.

Don't know if there could be done a user id check in entry point.
For us at the moment, this hack is working, as we all have User ID 1000.

2021-03-26 14:43 UTC, ihor-sviziev commented
@alinalexandru maybe we can introduce a new variable that will be set similar to this?
https://github.com/davidalger/warden/blob/5d1843bca3f6ed0ebc8615d651db4bc57765bb91/commands/env.cmd#L46-L49

2021-03-26 15:33 UTC, alinalexandru commented
That it's a good ideea, it might solve this issue for most of the linux users.

2021-03-26 19:44 UTC, ihor-sviziev requested changes
Could you update your solution with suggested in comments changes?

2021-03-29 07:42 UTC, alinalexandru commented
Yes, I will work on that today.

2021-03-30 09:10 UTC, ihor-sviziev approved these changes

2021-04-01 11:19 UTC, springerin commented
Any updates on when this can be release? 

Great job @alinalexandru for the debug. Thank you very much, i am having this issue very often now and couldn't figure out what was happening.

2021-04-01 19:52 UTC, ihor-sviziev commented
@davidalger could you review this PR?

2021-04-02 22:21 UTC, davidalger commented
LG2M as well. Thanks for the efforts at guiding this one @ihor-sviziev. Going to merge it, and once I have a chance to verify on my Linux box over here and update the CL will tag a release.

2021-04-02 22:21 UTC, merged