Environment and image build improvements
davidalger/warden pull request #363
Opened 2021-04-23 07:10 UTC by Den4ik

This PR is replace for https://github.com/davidalger/warden/pull/357

It would be great have ability to define repositories via CI variables or at warden `.env` files.
This PR provide improvements for image build and environment usage:
* Allow define custom php source and push repository at image build process
* Allow define custom warden source repository for environments

**Ref. PR** https://github.com/davidalger/warden/pull/345

2021-07-01 11:16 UTC, ihor-sviziev requested changes

2021-07-01 11:16 UTC, ihor-sviziev commented on images/scripts/build.sh
> +        pwd
Please revert code re-formatting in the file

2021-07-05 12:38 UTC, ihor-sviziev approved these changes

2021-07-21 08:06 UTC, ihor-sviziev commented
@davidalger, could you review this PR?

2021-07-24 21:28 UTC, merged

2021-07-24 21:33 UTC, davidalger commented
Merge commit 4daedec. Made a couple tweaks, to keep the docker.io prefix on the names, and use var name WARDEN_IMAGE_REPOSITORY vs WARDEN_SOURCE_REPOSITORY.

2021-07-24 21:34 UTC, davidalger commented
Thanks for the efforts here! It's good flexibility to have.