Feature/add tableplus command
davidalger/warden pull request #493
Opened 2022-02-22 10:16 UTC by rbouma

PR for feature described in: https://github.com/davidalger/warden/issues/449

2022-02-22 10:18 UTC, rbouma commented
@davidalger I removed the install changes for de identifyFile in de ssh config so this is only for the table plus command.

2022-02-22 16:00 UTC, ihor-sviziev requested changes

2022-02-22 16:13 UTC, tdgroot commented
Not a big fan of this feature. Not everyone is using tableplus, it's a non-free program and it feels like feature creep to me. I'd rather have detailed guides in the docs on how to configure a database editor.

2022-04-04 03:06 UTC, davidalger commented
Tend to agree with @tdgroot's reasoning on this one. Personally a huge fan of Table Plus, but integrations and shortcuts with every possible database client isn't something this project can reasonably be expected to have. What I would recommend is putting your work here into your project's `.warden/commands` directory, or placing it at `~/.warden/commands/tableplus.cmd` where Warden should load it (https://github.com/davidalger/warden/blob/develop/bin/warden#L50-L77) and be able to execute it from anywhere.

2022-04-04 03:06 UTC, closed without merging